# Generated by Django 4.2.7 on 2025-12-20 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='User who created this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(help_text="Price in format: '720,000' or '720,000 TZS' (commas auto-added)", max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['creator'], name='api_product_creator_a61159_idx'),
        ),
    ]
