# Generated by Django 4.2.7 on 2025-12-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_creator_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, help_text='Whether this product is marked as trending'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['trending'], name='api_product_trendin_ed6004_idx'),
        ),
    ]
