# Generated by Django 4.2.7 on 2026-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_trending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptops', 'Laptops'), ('Desktops', 'Desktops'), ('Gaming PCs', 'Gaming PCs'), ('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Phone', 'Phone')], help_text='Product category', max_length=50),
        ),
    ]
